// const autoCompleteData1 = {
//   ingredients: [
//     "snails",
//     "butter",
//     "mushrooms",
//     "garlic",
//     "shredded mozzarella cheese",
//     "fresh parsley",
//     "garbanzo beans",
//     "onions",
//     "flour",
//     "salt",
//     "cumin",
//     "ground coriander",
//     "black pepper",
//     "cayenne pepper",
//     "ground cardamom",
//     "vegetable oil",
//     "filet",
//     "olive oil",
//     "pepper",
//     "russet potatoes",
//     "beer",
//     "all-purpose flour",
//     "cod fillets",
//     "freshly ground pepper",
//     "chili powder",
//     "old bay seasoning",
//     "malt vinegar",
//     "foie gras",
//     "kosher salt",
//     "milk",
//     "large potatoes",
//     "frying oil",
//     "oil",
//     "sugar",
//     "beef broth",
//     "dry vermouth",
//     "baguette",
//     "garlic cloves",
//     "gruyere cheese",
//     "eggs",
//     "vanilla extract",
//     "cinnamon",
//     "powdered sugar",
//     "maple syrup",
//     "calamari",
//     "masa harina",
//     "parsley leaves",
//     "Meyer lemons",
//     "mayonnaise",
//     "cooked brown rice",
//     "sesame oil",
//     "frozen peas",
//     "shredded carrots",
//     "minced garlic",
//     "whole milk Greek yogurt",
//     "cream of tartar",
//     "egg whites",
//     "tomatoes",
//     "cherry tomatoes",
//     "purple onion",
//     "seedless cucumber",
//     "red bell pepper",
//     "romaine lettuce",
//     "fresh thyme",
//     "fresh chives",
//     "Greek feta",
//     "pitted kalamata olives",
//     "red wine vinegar",
//     "dried oregano",
//     "ground black pepper",
//     "rye bread",
//     "cheddar cheese",
//     "sweet onion",
//     "salmon fillets",
//     "brown sugar",
//     "seasoning",
//     "lemon juice",
//     "lemon",
//     "soy sauce",
//     "water",
//     "avocado",
//     "jalapeno chilies",
//     "cilantro leaves",
//     "coarse salt",
//     "lime",
//     "cabbage",
//     "ground pork",
//     "green onions",
//     "sake",
//     "corn starch",
//     "gyoza wrappers",
//     "rice vinegar",
//     "chili oil",
//     "beef",
//     "American cheese slices",
//     "ketchup",
//     "yellow mustard",
//     "dill pickles",
//     "hot sauce",
//     "lettuce",
//     "reduced sodium chicken broth",
//     "crushed red pepper",
//     "shiitake",
//     "large eggs",
//     "firm tofu",
//     "fresh ginger",
//     "scallions",
//     "hot dogs",
//     "hot dog bun",
//     "chili",
//     "mustard",
//     "sweet relish",
//     "Anaheim chile",
//     "ground cumin",
//     "adobo sauce",
//     "corn tortillas",
//     "fresh cilantro",
//     "chickpeas",
//     "tahini",
//     "finely chopped fresh parsley",
//     "cocoa powder",
//     "whole milk",
//     "heavy cream",
//     "vanilla",
//     "pork sausages",
//     "chopped onion",
//     "diced tomatoes",
//     "tomato sauce",
//     "Italian seasoning",
//     "fennel seeds",
//     "lasagna noodles",
//     "ricotta cheese",
//     "grated parmesan cheese",
//     "flat leaf parsley",
//     "thyme",
//     "fresh bay leaves",
//     "lobster",
//     "extra-virgin olive oil",
//     "brandy",
//     "shallots",
//     "carrots",
//     "celery",
//     "yellow onion",
//     "tomato paste",
//     "white wine",
//     "fish stock",
//     "egg yolks",
//     "chives",
//     "dijon mustard",
//     "fresh lemon juice",
//     "lobster meat",
//     "lettuce leaves",
//     "hot dog rolls",
//     "elbow macaroni",
//     "sharp cheddar cheese",
//     "almond flour",
//     "granulated sugar",
//     "soba noodles",
//     "miso",
//     "watercress",
//     "cilantro",
//     "red pepper flakes",
//     "white miso",
//     "apple cider vinegar",
//     "turmeric",
//     "mussels",
//     "dry white wine",
//     "chopped parsley",
//     "crusty bread",
//     "tortilla chips",
//     "ground beef",
//     "black beans",
//     "chunky salsa",
//     "shredded Monterey Jack cheese",
//     "pickled jalapenos",
//     "sour cream",
//     "cream cheese",
//     "chillies",
//     "dill",
//     "smoked salmon",
//     "baking powder",
//     "dry bread crumbs",
//     "olive oil cooking spray",
//     "cream",
//     "shucked oysters",
//     "salt and ground black pepper",
//     "rice noodles",
//     "boiling water",
//     "red chili peppers",
//     "large shrimp",
//     "oyster sauce",
//     "Thai fish sauce",
//     "fresh lime juice",
//     "beansprouts",
//     "unsalted roasted peanuts",
//     "paella rice",
//     "chorizo",
//     "boneless skinless chicken thighs",
//     "chicken stock",
//     "canned chopped tomatoes",
//     "saffron",
//     "sweet paprika",
//     "littleneck clams",
//     "lemon wedges",
//     "plain flour",
//     "buttermilk",
//     "pancake",
//     "streaky bacon",
//     "sun-dried tomatoes",
//     "feta cheese",
//     "freshly ground black pepper",
//     "unflavored gelatin",
//     "cold water",
//     "duck",
//     "ground cinnamon",
//     "ground ginger",
//     "ground nutmeg",
//     "ground white pepper",
//     "ground cloves",
//     "honey",
//     "orange",
//     "plum jam",
//     "white vinegar",
//     "chutney",
//     "marrow",
//     "oxtails",
//     "beef brisket",
//     "clove",
//     "star anise",
//     "black cardamom pods",
//     "black peppercorns",
//     "coriander seeds",
//     "ginger",
//     "Vietnamese fish sauce",
//     "yellow rock sugar",
//     "eye of the round",
//     "Thai basil",
//     "lime wedges",
//     "bird chile",
//     "chile sauce",
//     "hoisin sauce",
//     "pizza doughs",
//     "pitted black olives",
//     "oregano",
//     "fresh basil leaves",
//     "mozzarella cheese",
//     "pork chops",
//     "orange juice",
//     "lime juice",
//     "garlic powder",
//     "potatoes",
//     "canola oil",
//     "sauce",
//     "rib-eye roast",
//     "peppercorns",
//     "rosemary",
//     "jalapeno chiles",
//     "chipotle chile powder",
//     "paprika",
//     "worcestershire sauce",
//     "light brown sugar",
//     "bay leaf",
//     "shoulder roast",
//     "hamburger buns",
//     "dashi",
//     "ramen noodles",
//     "baby bok choy",
//     "radishes",
//     "sweet white miso",
//     "crushed red pepper flakes",
//     "cheese ravioli",
//     "pasta sauce",
//     "Swans Down Cake Flour",
//     "unsweetened cocoa powder",
//     "baking soda",
//     "red food coloring",
//     "vinegar",
//     "confectioners sugar",
//     "white chocolate curls",
//     "arborio rice",
//     "risotto",
//     "chicken broth",
//     "parmigiano reggiano cheese",
//     "rapeseed oil",
//     "cumin seed",
//     "garam masala",
//     "fresh coriander",
//     "pastry",
//     "sashimi grade tuna",
//     "mirin",
//     "sea scallops",
//     "cajun seasoning",
//     "ground cayenne pepper",
//     "greens",
//     "seaweed",
//     "sesame seeds",
//     "grits",
//     "unsalted butter",
//     "cheese",
//     "Tabasco Pepper Sauce",
//     "bacon slices",
//     "fat",
//     "white button mushrooms",
//     "sliced green onions",
//     "plum tomatoes",
//     "spaghetti",
//     "minced beef",
//     "pancetta",
//     "chopped tomatoes",
//     "red wine",
//     "white onion",
//     "fresh basil",
//     "bay leaves",
//     "sea salt",
//     "shaved parmesan cheese",
//     "bacon",
//     "fresh parsley leaves",
//     "spring roll wrappers",
//     "cucumber",
//     "toasted sesame seeds",
//     "top sirloin steak",
//     "montreal steak seasoning",
//     "strawberries",
//     "heavy whipping cream",
//     "biscuits",
//     "sushi rice",
//     "lean ground beef",
//     "salsa verde",
//     "konbu dashi",
//     "octopuses",
//     "Rice Krispies Cereal",
//     "shredded cheese",
//     "large egg yolks",
//     "mascarpone",
//     "brewed espresso",
//     "Frangelico",
//     "dark rum",
//     "lady fingers",
//     "sushi grade tuna",
//     "peeled fresh ginger",
//   ],
// };

export const autoCompleteData = [
  "snails",
  "butter",
  "mushrooms",
  "garlic",
  "shredded mozzarella cheese",
  "fresh parsley",
  "garbanzo beans",
  "onions",
  "flour",
  "salt",
  "cumin",
  "ground coriander",
  "black pepper",
  "cayenne pepper",
  "ground cardamom",
  "vegetable oil",
  "filet",
  "olive oil",
  "pepper",
  "russet potatoes",
  "beer",
  "all-purpose flour",
  "cod fillets",
  "freshly ground pepper",
  "chili powder",
  "old bay seasoning",
  "malt vinegar",
  "foie gras",
  "kosher salt",
  "milk",
  "large potatoes",
  "frying oil",
  "oil",
  "sugar",
  "beef broth",
  "dry vermouth",
  "baguette",
  "garlic cloves",
  "gruyere cheese",
  "eggs",
  "vanilla extract",
  "cinnamon",
  "powdered sugar",
  "maple syrup",
  "calamari",
  "masa harina",
  "parsley leaves",
  "Meyer lemons",
  "mayonnaise",
  "cooked brown rice",
  "sesame oil",
  "frozen peas",
  "shredded carrots",
  "minced garlic",
  "whole milk Greek yogurt",
  "cream of tartar",
  "egg whites",
  "tomatoes",
  "cherry tomatoes",
  "purple onion",
  "seedless cucumber",
  "red bell pepper",
  "romaine lettuce",
  "fresh thyme",
  "fresh chives",
  "Greek feta",
  "pitted kalamata olives",
  "red wine vinegar",
  "dried oregano",
  "ground black pepper",
  "rye bread",
  "cheddar cheese",
  "sweet onion",
  "salmon fillets",
  "brown sugar",
  "seasoning",
  "lemon juice",
  "lemon",
  "soy sauce",
  "water",
  "avocado",
  "jalapeno chilies",
  "cilantro leaves",
  "coarse salt",
  "lime",
  "cabbage",
  "ground pork",
  "green onions",
  "sake",
  "corn starch",
  "gyoza wrappers",
  "rice vinegar",
  "chili oil",
  "beef",
  "American cheese slices",
  "ketchup",
  "yellow mustard",
  "dill pickles",
  "hot sauce",
  "lettuce",
  "reduced sodium chicken broth",
  "crushed red pepper",
  "shiitake",
  "large eggs",
  "firm tofu",
  "fresh ginger",
  "scallions",
  "hot dogs",
  "hot dog bun",
  "chili",
  "mustard",
  "sweet relish",
  "Anaheim chile",
  "ground cumin",
  "adobo sauce",
  "corn tortillas",
  "fresh cilantro",
  "chickpeas",
  "tahini",
  "finely chopped fresh parsley",
  "cocoa powder",
  "whole milk",
  "heavy cream",
  "vanilla",
  "pork sausages",
  "chopped onion",
  "diced tomatoes",
  "tomato sauce",
  "Italian seasoning",
  "fennel seeds",
  "lasagna noodles",
  "ricotta cheese",
  "grated parmesan cheese",
  "flat leaf parsley",
  "thyme",
  "fresh bay leaves",
  "lobster",
  "extra-virgin olive oil",
  "brandy",
  "shallots",
  "carrots",
  "celery",
  "yellow onion",
  "tomato paste",
  "white wine",
  "fish stock",
  "egg yolks",
  "chives",
  "dijon mustard",
  "fresh lemon juice",
  "lobster meat",
  "lettuce leaves",
  "hot dog rolls",
  "elbow macaroni",
  "sharp cheddar cheese",
  "almond flour",
  "granulated sugar",
  "soba noodles",
  "miso",
  "watercress",
  "cilantro",
  "red pepper flakes",
  "white miso",
  "apple cider vinegar",
  "turmeric",
  "mussels",
  "dry white wine",
  "chopped parsley",
  "crusty bread",
  "tortilla chips",
  "ground beef",
  "black beans",
  "chunky salsa",
  "shredded Monterey Jack cheese",
  "pickled jalapenos",
  "sour cream",
  "cream cheese",
  "chillies",
  "dill",
  "smoked salmon",
  "baking powder",
  "dry bread crumbs",
  "olive oil cooking spray",
  "cream",
  "shucked oysters",
  "salt and ground black pepper",
  "rice noodles",
  "boiling water",
  "red chili peppers",
  "large shrimp",
  "oyster sauce",
  "Thai fish sauce",
  "fresh lime juice",
  "beansprouts",
  "unsalted roasted peanuts",
  "paella rice",
  "chorizo",
  "boneless skinless chicken thighs",
  "chicken stock",
  "canned chopped tomatoes",
  "saffron",
  "sweet paprika",
  "littleneck clams",
  "lemon wedges",
  "plain flour",
  "buttermilk",
  "pancake",
  "streaky bacon",
  "sun-dried tomatoes",
  "feta cheese",
  "freshly ground black pepper",
  "unflavored gelatin",
  "cold water",
  "duck",
  "ground cinnamon",
  "ground ginger",
  "ground nutmeg",
  "ground white pepper",
  "ground cloves",
  "honey",
  "orange",
  "plum jam",
  "white vinegar",
  "chutney",
  "marrow",
  "oxtails",
  "beef brisket",
  "clove",
  "star anise",
  "black cardamom pods",
  "black peppercorns",
  "coriander seeds",
  "ginger",
  "Vietnamese fish sauce",
  "yellow rock sugar",
  "eye of the round",
  "Thai basil",
  "lime wedges",
  "bird chile",
  "chile sauce",
  "hoisin sauce",
  "pizza doughs",
  "pitted black olives",
  "oregano",
  "fresh basil leaves",
  "mozzarella cheese",
  "pork chops",
  "orange juice",
  "lime juice",
  "garlic powder",
  "potatoes",
  "canola oil",
  "sauce",
  "rib-eye roast",
  "peppercorns",
  "rosemary",
  "jalapeno chiles",
  "chipotle chile powder",
  "paprika",
  "worcestershire sauce",
  "light brown sugar",
  "bay leaf",
  "shoulder roast",
  "hamburger buns",
  "dashi",
  "ramen noodles",
  "baby bok choy",
  "radishes",
  "sweet white miso",
  "crushed red pepper flakes",
  "cheese ravioli",
  "pasta sauce",
  "Swans Down Cake Flour",
  "unsweetened cocoa powder",
  "baking soda",
  "red food coloring",
  "vinegar",
  "confectioners sugar",
  "white chocolate curls",
  "arborio rice",
  "risotto",
  "chicken broth",
  "parmigiano reggiano cheese",
  "rapeseed oil",
  "cumin seed",
  "garam masala",
  "fresh coriander",
  "pastry",
  "sashimi grade tuna",
  "mirin",
  "sea scallops",
  "cajun seasoning",
  "ground cayenne pepper",
  "greens",
  "seaweed",
  "sesame seeds",
  "grits",
  "unsalted butter",
  "cheese",
  "Tabasco Pepper Sauce",
  "bacon slices",
  "fat",
  "white button mushrooms",
  "sliced green onions",
  "plum tomatoes",
  "spaghetti",
  "minced beef",
  "pancetta",
  "chopped tomatoes",
  "red wine",
  "white onion",
  "fresh basil",
  "bay leaves",
  "sea salt",
  "shaved parmesan cheese",
  "bacon",
  "fresh parsley leaves",
  "spring roll wrappers",
  "cucumber",
  "toasted sesame seeds",
  "top sirloin steak",
  "montreal steak seasoning",
  "strawberries",
  "heavy whipping cream",
  "biscuits",
  "sushi rice",
  "lean ground beef",
  "salsa verde",
  "konbu dashi",
  "octopuses",
  "Rice Krispies Cereal",
  "shredded cheese",
  "large egg yolks",
  "mascarpone",
  "brewed espresso",
  "Frangelico",
  "dark rum",
  "lady fingers",
  "sushi grade tuna",
  "peeled fresh ginger",
];
